# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkgO4PoWBrXKMpEbmiUGf3CMxANDzjP2
"""

import os
import io
import requests
import pandas as pd
import asyncio
from datetime import datetime
from telegram import Bot

async def main():
    bot_token = os.environ.get('TELEGRAM_TOKEN')
    my_chat_id = os.environ.get('MY_CHAT_ID')
    channel_chat_id = os.environ.get('CHANNEL_CHAT_ID')
    bot = Bot(token=bot_token)

    today_str = datetime.now().strftime("%Y-%m-%d")
    url = "https://finance.yahoo.com/markets/stocks/large-cap-stocks/?start=0&count=100"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

    try:
        # 1. 데이터 수집
        response = requests.get(url, headers=headers)
        tables = pd.read_html(io.StringIO(response.text))
        df = tables[0].head(15).copy() # 테스트용 상위 15개

        # 날짜 및 필요 컬럼 추가
        df['Date'] = today_str
        df['Change_Score'] = df['% Change'].astype(str).str.replace('%', '').str.replace('+', '').str.replace(',', '')
        df['Change_Score'] = pd.to_numeric(df['Change_Score'], errors='coerce').fillna(0)

        # 음수면 50 -> -25점 (2로 나누고 뺌) 처리
        df['Final_Score'] = df['Change_Score'].apply(lambda x: -(50/2) if x < 0 else 50)

        # 2. [무한 데이터] 저장 (계속 누적)
        infinite_file = 'us_infinite.csv'
        if os.path.exists(infinite_file):
            inf_df = pd.read_csv(infinite_file)
            inf_df = pd.concat([inf_df, df])
        else:
            inf_df = df
        inf_df.to_csv(infinite_file, index=False)

        # 3. [20일 데이터] 저장 (최근 20일치 날짜만 유지)
        recent_file = 'us_20days.csv'
        if os.path.exists(recent_file):
            df20 = pd.read_csv(recent_file)
            df20 = pd.concat([df20, df])
            # 고유 날짜를 추출하여 최근 20개만 필터링
            unique_dates = df20['Date'].unique()
            if len(unique_dates) > 20:
                recent_dates = unique_dates[-20:]
                df20 = df20[df20['Date'].isin(recent_dates)]
        else:
            df20 = df
        df20.to_csv(recent_file, index=False)

        # 4. [나에게] 고급 정보 메시지 생성 및 전송
        advanced_info = f"📊 [US 대형주 고급 분석 - {today_str}]\n\n"
        for _, row in df.iterrows():
            advanced_info += f"[{row['Symbol']}] {row['Name']}\n현재가: {row['Price (Intraday)']} | 등락률: {row['% Change']}\n💡 점수: {row['Final_Score']}점\n\n"
        await bot.send_message(chat_id=my_chat_id, text=advanced_info)

        # 5. [친구에게] 채널용 일반 정보 메시지 생성 및 전송 (점수 양수만)
        channel_info = f"📈 [R2D2 추천 미국 주식 - {today_str}]\n\n"
        good_stocks = df[df['Final_Score'] > 0]
        for _, row in good_stocks.iterrows():
            channel_info += f"• {row['Symbol']} ({row['Name']}) : {row['Price (Intraday)']}\n"
        if channel_chat_id:
            await bot.send_message(chat_id=channel_chat_id, text=channel_info)

    except Exception as e:
        await bot.send_message(chat_id=my_chat_id, text=f"에러 발생: {e}")

if __name__ == "__main__":
    asyncio.run(main())